# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sha Todo List' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sha Todo List
  pod 'RealmSwift'
  pod 'SwipeCellKit'
end
